sudo: required
dist: bionic

language: node_js
node_js:
  - "12"
  - "13"
  - "14"

before_install:
 - sudo apt-get update
 - sudo apt-get install -y dpkg  # to upgrade to dpkg >= 1.17.5ubuntu5.8, which fixes https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 - google-chrome --version

install:
  - yarn

before_script:
  - yarn lint

script:
  - yarn test:ci
